apiVersion: v1
kind: Pod
metadata:
  name: load-generator
  namespace: demo-standard
spec:
  containers:
  - name: stress
    image: busybox
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    resources:
      requests:
        cpu: "850m" # 85% of 1000m -> Triggers resize (Threshold 80%)
        memory: "100Mi"
