apiVersion: v1
kind: Pod
metadata:
  name: load-generator
  namespace: demo-standard
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      resources:
        requests:
          cpu: "850m"
