apiVersion: v1
kind: ResourceQuota
metadata:
  name: standard-quota
  namespace: demo-standard
spec:
  hard:
    requests.cpu: "1200m"
    requests.memory: "1Gi"
    limits.cpu: "2000m"
    limits.memory: "2Gi"
