apiVersion: v1
kind: Pod
metadata:
  name: load-generator
  namespace: demo-custom
spec:
  containers:
  - name: stress
    image: busybox
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    resources:
      requests:
        cpu: "600m" # 60% > 50% -> Triggers resize
        memory: "100Mi"
