apiVersion: v1
kind: Pod
metadata:
  name: sensitive-pod
  namespace: demo-custom
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      resources:
        requests:
          cpu: "600m"
