apiVersion: v1
kind: Pod
metadata:
  name: ignored-pod
  namespace: demo-opt-out
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      resources:
        requests:
          cpu: "900m"
