apiVersion: v1
kind: Pod
metadata:
  name: load-generator
  namespace: demo-opt-out
spec:
  containers:
  - name: stress
    image: busybox
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    resources:
      requests:
        cpu: "900m" # 90% > 80% -> But ignored due to opt-out
        memory: "100Mi"
