apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: burst-sts
  namespace: demo-statefulset-burst
spec:
  serviceName: "burst"
  replicas: 3
  selector:
    matchLabels:
      app: burst
  template:
    metadata:
      labels:
        app: burst
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          requests:
            cpu: "200m"
            memory: "50Mi"
