apiVersion: v1
kind: Namespace
metadata:
  name: demo-dual-pressure
  annotations:
    resizer.io/enabled: "true"
    resizer.io/threshold: "80"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dual-quota
  namespace: demo-dual-pressure
spec:
  hard:
    requests.cpu: "1200m"
    requests.memory: "1229Mi"
    limits.cpu: "2000m"
    limits.memory: "2Gi"
---
apiVersion: v1
kind: Pod
metadata:
  name: dual-stress
  namespace: demo-dual-pressure
spec:
  containers:
    - name: stress
      image: busybox
      command: ["sh", "-c", "while true; do sleep 3600; done"]
      resources:
        requests:
          cpu: "900m" # 90%
          memory: "900Mi" # ~88%
        limits:
          cpu: "1000m"
          memory: "1Gi"
