apiVersion: v1
kind: Namespace
metadata:
  name: demo-storage
  annotations:
    resizer.io/enabled: "true"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage-quota
  namespace: demo-storage
spec:
  hard:
    requests.storage: "5Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: large-pvc
  namespace: demo-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "6Gi" # 6Gi > 5Gi -> FailedCreate -> Resize
