apiVersion: v1
kind: Namespace
metadata:
  name: demo-storage
  annotations:
    resizer.io/enabled: "true"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage-quota
  namespace: demo-storage
spec:
  hard:
    requests.storage: 7373Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage-stress
  namespace: demo-storage
spec:
  serviceName: "storage"
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
        - name: nginx
          image: nginx
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 7373Mi
